"""
Creative Corpus Evaluator & Internal Cliché Detector:
Audits large corpora of generated sessions (N = 20 to 100+) to observe emergent behavior
and prevent the engine from developing its own internal clichés.

Features:
1. Contextual Mechanism Categorization (HARD, SOFT, OPTIONAL, IDENTITY)
2. Selective Cliché Detection (only discretionary OPTIONAL techniques trigger alarms)
3. Advanced Section Distribution & Co-occurrence Matrix
4. Underutilization Auditing (< 5% usage across corpus)
5. Resampling depth, survival rates, and Music Director rollback tracking
"""

import logging
from enum import Enum
from typing import Dict, Any, List, Optional
import math

from engine.creative.resampling_lab import GenealogyTree

logger = logging.getLogger("CreativeCorpusEvaluator")

CLICHE_FREQUENCY_THRESHOLD: float = 0.85  # >= 85% usage for OPTIONAL techniques flags internal cliché


class MechanismCategory(Enum):
    """
    Categorization of production mechanisms to distinguish canonical structural rules
    from discretionary creative flourishes.
    """
    HARD = "HARD"          # Canonical / structural rule (pre-drop vacuum, 4/4 anchor, frequency slotting). Expected 90-100%. Exempt from cliché alarms.
    SOFT = "SOFT"          # Recommended stylistic convention (foley bed, organic groove). Informational only.
    OPTIONAL = "OPTIONAL"  # Discretionary creative technique (3/16 polyrhythm, reverse audio, deep resampling). Cliché alarm active when overused.
    IDENTITY = "IDENTITY"  # Unique song signature / motif.


MECHANISM_CATALOG: Dict[str, MechanismCategory] = {
    # Optional creative techniques (eligible for cliché alarms)
    "polyrhythm_3_16": MechanismCategory.OPTIONAL,
    "reverse_audio_transition": MechanismCategory.OPTIONAL,
    "reverse_transition": MechanismCategory.OPTIONAL,
    "reverse_audio": MechanismCategory.OPTIONAL,
    "resampling_depth_3": MechanismCategory.OPTIONAL,
    "vocal_hook_chop": MechanismCategory.OPTIONAL,
    
    # Soft conventions
    "foley_bed": MechanismCategory.SOFT,
    "foley_organic_layer": MechanismCategory.SOFT,
    "organic_groove_humanize": MechanismCategory.SOFT,
    
    # Hard canonical rules (exempt from cliché alarms)
    "pre_drop_stereo_collapse": MechanismCategory.HARD,
    "pre_drop_vacuum": MechanismCategory.HARD,
    "metric_anchor_4_4": MechanismCategory.HARD,
    "frequency_slotting": MechanismCategory.HARD,
}


class CreativeCorpusEvaluator:
    """
    Observes and audits a corpus of songs/sessions generated by the engine
    without modifying them, detecting emergent patterns, systemic biases,
    and contextual clichés.
    """

    @classmethod
    def get_mechanism_category(cls, technique_name: str) -> MechanismCategory:
        """Returns the MechanismCategory for a given technique, defaulting to OPTIONAL."""
        return MECHANISM_CATALOG.get(technique_name.lower().strip(), MechanismCategory.OPTIONAL)

    @classmethod
    def register_mechanism(cls, technique_name: str, category: MechanismCategory) -> None:
        """Registers or updates a technique's category."""
        MECHANISM_CATALOG[technique_name.lower().strip()] = category

    @classmethod
    def evaluate_corpus(
        cls,
        sessions: List[Any],
        cliche_threshold: float = CLICHE_FREQUENCY_THRESHOLD
    ) -> Dict[str, Any]:
        """
        Audits a corpus of sessions, calculating frequencies, evolutionary metrics,
        section distribution, co-occurrence, and contextual cliché alarms.
        """
        if not sessions:
            return {
                "status": "EMPTY_CORPUS",
                "message": "No hay sesiones disponibles para auditar.",
                "total_sessions": 0
            }

        total_sessions = len(sessions)

        polyrhythm_count = 0
        stereo_collapse_count = 0
        reverse_transition_count = 0
        foley_count = 0
        resampling_depth_3_count = 0
        metric_anchor_count = 0
        frequency_slotting_count = 0

        resampling_depths: List[int] = []
        survival_rates: List[float] = []
        director_mutations_count = 0
        director_rollbacks_count = 0

        identity_scores: List[float] = []
        contrast_scores: List[float] = []
        coherence_scores: List[float] = []

        # Tracking for section distribution and co-occurrence
        session_active_sets: List[set] = []
        all_session_sections: Dict[str, List[str]] = {
            "polyrhythm_3_16": [],
            "pre_drop_stereo_collapse": [],
            "reverse_audio_transition": [],
            "foley_bed": [],
            "resampling_depth_3": []
        }
        custom_mechanism_counts: Dict[str, int] = {}

        for s in sessions:
            data = s.data if hasattr(s, "data") else (s if isinstance(s, dict) else {})
            tracks = data.get("tracks", [])
            sections = data.get("sections", [])
            ident_data = data.get("music_identity", {})
            applied_mechanisms = set(str(m).lower() for m in data.get("applied_mechanisms", []))

            active_in_session: set = set()

            # 1. Metric tension / polyrhythm detection
            has_polyrhythm = any(
                any(n.get("is_metric_tension", False) for n in t.get("notes", [])) or
                "3/16" in str(t.get("name", "")) or "5/16" in str(t.get("name", ""))
                for t in tracks
            ) or ("polyrhythm_3_16" in applied_mechanisms)
            if has_polyrhythm:
                polyrhythm_count += 1
                active_in_session.add("polyrhythm_3_16")
                # Section mapping
                poly_sections = [
                    str(t.get("section", "build")).lower()
                    for t in tracks
                    if any(n.get("is_metric_tension", False) for n in t.get("notes", [])) or "3/16" in str(t.get("name", ""))
                ] or ["build"]
                all_session_sections["polyrhythm_3_16"].extend(poly_sections)

            # 2. Stereo collapse detection (pre-drop width <= 0.20)
            spatial_curve = data.get("spatial_energy_curve", [])
            has_collapse = any(
                pt.get("stereo_width", 1.0) <= 0.20 or
                pt.get("profile", {}).get("stereo_width", 1.0) <= 0.20
                for pt in spatial_curve
            ) or any("pre_drop" in s.get("name", "").lower() for s in sections) or (
                "pre_drop_vacuum" in applied_mechanisms or
                "pre_drop_stereo_collapse" in applied_mechanisms or
                data.get("pre_drop_vacuum_verified", False)
            )
            if has_collapse:
                stereo_collapse_count += 1
                active_in_session.add("pre_drop_stereo_collapse")
                active_in_session.add("pre_drop_vacuum")
                all_session_sections["pre_drop_stereo_collapse"].append("pre_drop")

            # 3. Reverse transition detection
            genealogy = ident_data.get("genealogy_log", []) if isinstance(ident_data, dict) else []
            has_reverse = any(
                any("reverse" in str(tr).lower() for tr in g.get("transformations", []))
                for g in genealogy
            ) or any("reverse" in str(t.get("name", "")).lower() for t in tracks) or (
                "reverse_audio" in applied_mechanisms or
                "reverse_audio_transition" in applied_mechanisms or
                "reverse_transition" in applied_mechanisms
            )
            if has_reverse:
                reverse_transition_count += 1
                active_in_session.add("reverse_audio_transition")
                active_in_session.add("reverse_transition")
                active_in_session.add("reverse_audio")
                all_session_sections["reverse_audio_transition"].append("build")

            # 4. Foley / texture layer detection
            has_foley = any(
                str(t.get("role", "")).upper() in ("TEXTURE_FOLEY", "FOLEY") or
                "foley" in str(t.get("name", "")).lower() or
                "texture" in str(t.get("name", "")).lower()
                for t in tracks
            ) or ("foley_bed" in applied_mechanisms or "foley_organic_layer" in applied_mechanisms)
            if has_foley:
                foley_count += 1
                active_in_session.add("foley_bed")
                active_in_session.add("foley_organic_layer")
                all_session_sections["foley_bed"].append("intro")

            # 5. Resampling depth and survival
            gen_sources = data.get("generated_sources", [])
            has_depth_3 = False
            if gen_sources:
                surv_data = GenealogyTree.calculate_survival_rate(data)
                survival_rates.append(surv_data.get("survival_rate", 0.0))
                max_d = surv_data.get("max_depth", 1)
                resampling_depths.append(max_d)
                if max_d >= 3:
                    has_depth_3 = True
            if has_depth_3 or ("resampling_depth_3" in applied_mechanisms):
                resampling_depth_3_count += 1
                active_in_session.add("resampling_depth_3")
                all_session_sections["resampling_depth_3"].append("breakdown")

            # 6. Canonical anchors (metric anchor 4/4 & frequency slotting)
            has_anchor = any(
                str(t.get("role", "")).upper() in ("KICK", "SNARE", "CLAP", "DRUMS")
                for t in tracks
            ) or ("metric_anchor_4_4" in applied_mechanisms) or len(tracks) > 0
            if has_anchor:
                metric_anchor_count += 1
                active_in_session.add("metric_anchor_4_4")

            has_slotting = data.get("frequency_slotting_applied", False) or (
                "frequency_slotting" in applied_mechanisms
            )
            if has_slotting:
                frequency_slotting_count += 1
                active_in_session.add("frequency_slotting")

            # Register custom applied mechanisms
            for m in applied_mechanisms:
                active_in_session.add(m)
                custom_mechanism_counts[m] = custom_mechanism_counts.get(m, 0) + 1

            session_active_sets.append(active_in_session)

            # 7. Director mutations & rollbacks
            director_audit = data.get("music_director_history", [])
            for h in director_audit:
                if h.get("status") == "MUTATION_COMMITTED":
                    director_mutations_count += 1
                elif h.get("status") == "ROLLBACK_EXECUTED":
                    director_rollbacks_count += 1

            # Scores
            if "identity_score" in data:
                identity_scores.append(float(data["identity_score"]))
            if "contrast_score" in data:
                contrast_scores.append(float(data["contrast_score"]))
            if "coherence_score" in data:
                coherence_scores.append(float(data["coherence_score"]))

        # Frequency calculations
        polyrhythm_freq = round(polyrhythm_count / total_sessions, 3)
        stereo_collapse_freq = round(stereo_collapse_count / total_sessions, 3)
        reverse_transition_freq = round(reverse_transition_count / total_sessions, 3)
        foley_freq = round(foley_count / total_sessions, 3)
        resampling_depth_3_freq = round(resampling_depth_3_count / total_sessions, 3)
        metric_anchor_freq = round(metric_anchor_count / total_sessions, 3)
        frequency_slotting_freq = round(frequency_slotting_count / total_sessions, 3)

        avg_depth = round(sum(resampling_depths) / len(resampling_depths), 2) if resampling_depths else 0.0
        avg_survival = round(sum(survival_rates) / len(survival_rates), 3) if survival_rates else 0.0

        frequencies: Dict[str, float] = {
            "polyrhythm_3_16": polyrhythm_freq,
            "stereo_collapse": stereo_collapse_freq,
            "pre_drop_stereo_collapse": stereo_collapse_freq,
            "pre_drop_vacuum": stereo_collapse_freq,
            "reverse_transition": reverse_transition_freq,
            "reverse_audio_transition": reverse_transition_freq,
            "reverse_audio": reverse_transition_freq,
            "foley_bed": foley_freq,
            "foley_organic_layer": foley_freq,
            "resampling_depth_3": resampling_depth_3_freq,
            "metric_anchor_4_4": metric_anchor_freq,
            "frequency_slotting": frequency_slotting_freq,
        }

        # Add custom mechanisms to frequencies
        for m, cnt in custom_mechanism_counts.items():
            if m not in frequencies:
                frequencies[m] = round(cnt / total_sessions, 3)

        # Contextual Cliché Alarms:
        # STRICT RULE: ONLY mechanisms categorized as OPTIONAL trigger cliché alarms.
        # HARD mechanisms (e.g. pre_drop_vacuum, metric_anchor_4_4) are canon and NEVER trigger alarms.
        cliche_alarms: List[Dict[str, Any]] = []

        eval_candidates = [
            ("polyrhythm_3_16", polyrhythm_freq, "Polirritmia 3/16 detectada en {pct} de las canciones. Riesgo de cliché interno.", "Reducir la probabilidad base de tensión métrica o incorporar patrones euclidianos alternativos."),
            ("reverse_audio_transition", reverse_transition_freq, "Transición reverse detectada en {pct} de las canciones. Riesgo de cliché interno.", "Variar las fórmulas de transición (ej. noise sweep, parada con tape stop, caída de subgraves)."),
            ("resampling_depth_3", resampling_depth_3_freq, "Resampling de profundidad 3 detectado en {pct} de las canciones.", "Limitar profundidad de árbol a 2 para preservar inteligibilidad.")
        ]

        # Also check custom mechanisms
        for m, freq in frequencies.items():
            if m not in ("polyrhythm_3_16", "reverse_audio_transition", "resampling_depth_3", "stereo_collapse", "pre_drop_stereo_collapse", "pre_drop_vacuum", "reverse_transition", "reverse_audio", "foley_bed", "foley_organic_layer", "metric_anchor_4_4", "frequency_slotting"):
                cat = cls.get_mechanism_category(m)
                if cat == MechanismCategory.OPTIONAL and freq >= cliche_threshold:
                    eval_candidates.append((
                        m,
                        freq,
                        f"Técnica opcional '{m}' detectada en {{pct}} de las canciones. Riesgo de cliché interno.",
                        "Introducir mayor alternancia y variedad en la selección de esta técnica."
                    ))

        for tech_key, freq_val, warn_template, rec in eval_candidates:
            cat = cls.get_mechanism_category(tech_key)
            if cat == MechanismCategory.OPTIONAL and freq_val >= cliche_threshold:
                cliche_alarms.append({
                    "technique": tech_key,
                    "category": cat.value,
                    "frequency": freq_val,
                    "warning": warn_template.format(pct=f"{freq_val * 100:.1f}%"),
                    "recommendation": rec
                })

        # Section Distribution
        section_distribution: Dict[str, Dict[str, int]] = {}
        for tech, sec_list in all_session_sections.items():
            sec_counts: Dict[str, int] = {}
            for sec in sec_list:
                sec_counts[sec] = sec_counts.get(sec, 0) + 1
            section_distribution[tech] = sec_counts

        # Co-occurrence Matrix
        tracked_keys = [
            "polyrhythm_3_16",
            "pre_drop_stereo_collapse",
            "reverse_audio_transition",
            "foley_bed",
            "resampling_depth_3"
        ]
        co_occurrence_matrix: Dict[str, Dict[str, float]] = {}
        for k1 in tracked_keys:
            co_occurrence_matrix[k1] = {}
            for k2 in tracked_keys:
                co_cnt = sum(1 for s_set in session_active_sets if k1 in s_set and k2 in s_set)
                co_occurrence_matrix[k1][k2] = round(co_cnt / total_sessions, 3)

        # Underutilized techniques (< 5% usage)
        underutilized_techniques = [
            tech for tech in ["polyrhythm_3_16", "reverse_audio_transition", "resampling_depth_3", "foley_bed"]
            if frequencies.get(tech, 0.0) < 0.05
        ]

        avg_ident = round(sum(identity_scores) / len(identity_scores), 2) if identity_scores else 0.70
        avg_contrast = round(sum(contrast_scores) / len(contrast_scores), 2) if contrast_scores else 0.60
        avg_coherence = round(sum(coherence_scores) / len(coherence_scores), 2) if coherence_scores else 0.80

        return {
            "status": "CORPUS_AUDITED",
            "total_sessions_analyzed": total_sessions,
            "has_internal_cliche_alarm": len(cliche_alarms) > 0,
            "cliche_alarms": cliche_alarms,
            "frequencies": frequencies,
            "mechanism_categories": {k: cls.get_mechanism_category(k).value for k in frequencies.keys()},
            "section_distribution": section_distribution,
            "co_occurrence_matrix": co_occurrence_matrix,
            "underutilized_techniques": underutilized_techniques,
            "resampling_metrics": {
                "average_depth": avg_depth,
                "average_survival_rate": avg_survival
            },
            "director_metrics": {
                "total_mutations_applied": director_mutations_count,
                "total_rollbacks_executed": director_rollbacks_count,
                "rollback_rate": round(
                    director_rollbacks_count / max(1, director_mutations_count + director_rollbacks_count),
                    3
                )
            },
            "corpus_averages": {
                "identity_score": avg_ident,
                "contrast_score": avg_contrast,
                "coherence_score": avg_coherence
            }
        }
