# engine/sound_design/valhalla_supermassive/sanitizer.py
"""
Sanitizer and Auto-Repair for Valhalla Supermassive.

Automatically clamps, repairs, and completes presets generated by AI
to guarantee 100% valid XML and deterministic DSP behavior.
"""

from typing import Tuple, List, Dict, Any
import math

from .model import SupermassiveModel
from .schema import ValhallaSupermassiveSchema


class SupermassiveSanitizer:
    """Clamps parameters and fixes common configuration flaws."""

    @classmethod
    def sanitize(cls, model: SupermassiveModel) -> Tuple[SupermassiveModel, List[str]]:
        """
        Sanitize a SupermassiveModel in-place or copied, returning (model, list_of_fixes).
        """
        repaired = model.copy()
        corrections: List[str] = []

        # Fix preset name
        if not repaired.preset_name or not repaired.preset_name.strip():
            repaired.preset_name = "Untitled"
            corrections.append("Defaulted empty presetName to 'Untitled'.")

        # Fix plugin version
        if not repaired.plugin_version or not repaired.plugin_version.strip():
            repaired.plugin_version = ValhallaSupermassiveSchema.DEFAULT_VERSION
            corrections.append(f"Defaulted pluginVersion to '{repaired.plugin_version}'.")

        # Parameters to clamp
        float_fields = [
            ("mix", 1.0),
            ("delay_sync", 0.25),
            ("delay_note", 0.285714298),
            ("delay_ms", 0.5),
            ("delay_warp", 0.5),
            ("clear", 0.0),
            ("feedback", 0.5),
            ("density", 0.5),
            ("width", 1.0),
            ("low_cut", 0.0),
            ("high_cut", 1.0),
            ("mod_rate", 0.5),
            ("mod_depth", 0.5),
            ("mode", 0.0),
            ("reserved1", 0.0),
            ("reserved2", 0.0),
            ("reserved3", 0.0),
            ("reserved4", 0.0),
        ]

        for field_name, default_val in float_fields:
            val = getattr(repaired, field_name)
            if val is None or not isinstance(val, (int, float)) or math.isnan(val) or math.isinf(val):
                setattr(repaired, field_name, default_val)
                corrections.append(f"Parameter '{field_name}' invalid ({val}), reset to {default_val}.")
            elif val < 0.0:
                setattr(repaired, field_name, 0.0)
                corrections.append(f"Clamped '{field_name}' from {val} up to 0.0.")
            elif val > 1.0:
                setattr(repaired, field_name, 1.0)
                corrections.append(f"Clamped '{field_name}' from {val} down to 1.0.")

        # Ensure clear is either 0.0 or 1.0
        if repaired.clear not in (0.0, 1.0):
            old = repaired.clear
            repaired.clear = 1.0 if repaired.clear >= 0.5 else 0.0
            corrections.append(f"Quantized clear button from {old} to {repaired.clear}.")

        return repaired, corrections
